service: sandbox-slackbolt

frameworkVersion: ">=3"

plugins:
  - serverless-python-requirements

provider:
  name: aws
  stage: dev
  region: us-east-1
  runtime: python3.9
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "ssm:*"
            - "ssm:GetParameter"
            - "ssm:GetParameters"
            - "ssm:GetParametersByPath"
            - "ssm:PutParameter"
            - "ssm:DeleteParameter"
            - "ssm:DeleteParameters"
          Resource:
            - "arn:aws:ssm:us-east-1:394573302243:parameter/SLACK_BOT_TOKEN"
            - "arn:aws:ssm:us-east-1:394573302243:parameter/SLACK_SIGNING_SECRET"


package:
  patterns:
    - "!README.md"
    - "!package.json"
    - "!node_modules/**"
    - "!package-lock.json"
    - "!slack_bolt_req.txt"


custom:
  pythonRequirements:
    dockerizePip: false
    fileName: slack_bolt_req.txt
    layer:
      name: slack_bolt_lib
      description: Slack Bolt layer built on the fly using dockerizePip.
      compatibleRuntimes:
        - python3.9
      compatibleArchitectures:
        - x86_64


functions:
  cc-command:
    url: true
    handler: handler.cccommand
    layers:
      - Ref: PythonRequirementsLambdaLayer
