name: GitHub Actions Scheduled Workflow.

run-name: ${{ github.actor }} Is Launching Scheduled Workflow. 🚀

on:
  schedule:
    - cron:  '38 11 28 5 0'

jobs:
  Job_To-Run_Scheduled_Jobs:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
